# Generated by Django 3.2 on 2021-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('field_gid', models.BigIntegerField(blank=True, db_column='__gid', null=True)),
                ('ddgn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('first_dcod', models.BigIntegerField(blank=True, null=True)),
                ('first_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('first_gn_c', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('first_stat', models.BigIntegerField(blank=True, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('centroid_x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('centroid_y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gapanapa',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('field_gid', models.BigIntegerField(blank=True, db_column='__gid', null=True)),
                ('objectid_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('palika', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('gapa_napa', models.CharField(blank=True, max_length=50, null=True)),
                ('gn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gapanapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('field_gid', models.BigIntegerField(blank=True, db_column='__gid', null=True)),
                ('ddgn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('first_dcod', models.BigIntegerField(blank=True, null=True)),
                ('first_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('first_gn_c', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('first_stat', models.BigIntegerField(blank=True, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
    ]
