# Generated by Django 3.2 on 2021-04-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layoutApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gapanapa',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
