# Generated by Django 3.2 on 2021-04-16 06:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layoutApp', '0003_auto_20210416_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('field_gid', models.BigIntegerField(blank=True, db_column='__gid', null=True)),
                ('ddgn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('first_dcod', models.BigIntegerField(blank=True, null=True)),
                ('first_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('first_gn_c', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('first_stat', models.BigIntegerField(blank=True, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('centroid_x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('centroid_y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
